# Generated by Django 3.2.16 on 2022-11-07 01:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('account_book', '0001_initial'), ('account_book', '0002_auto_20221105_0001'), ('account_book', '0003_alter_accountbook_name'), ('account_book', '0004_alter_memo_account_book_diary')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='가계부 이름을 지어 주세요.', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_book',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountBookDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(help_text='금액을 적어 주세요.', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(blank=True, choices=[('I', '수입'), ('E', '지출')], max_length=1)),
                ('is_delete', models.BooleanField(default=False, help_text='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_book.accountbook')),
            ],
            options={
                'db_table': 'account_book_diary',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='가계부 내용을 입력해주세요.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_book_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='account_book.accountbookdiary')),
            ],
            options={
                'db_table': 'memo',
            },
        ),
    ]
